In [1]:
#INSTALAR LIBRERIAS
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn
!pip install openpyxl
!pip install sympy

zsh:1: command not found: pip
zsh:1: command not found: pip
zsh:1: command not found: pip
zsh:1: command not found: pip
zsh:1: command not found: pip
zsh:1: command not found: pip


In [2]:
%pip install sympy

Note: you may need to restart the kernel to use updated packages.


In [3]:
%pip install seaborn

Note: you may need to restart the kernel to use updated packages.


In [4]:
%pip install matplotlib

Note: you may need to restart the kernel to use updated packages.


In [5]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sympy import primerange

In [6]:
#Convertimos el dataset en dataframe
df= pd.read_csv("Mexico_city.csv")
df

,id,name,host_id,host_profile_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,1698274831948209016,Roma Residence | Luxury Suite 305,471105419,1.470125e+18,Manuel,NaN,Cuauhtémoc,19.406572,-99.163091,Entire home/apt,2066.0,1.0,0,NaN,NaN,42,365,0,NaN
1,1120444645818769896,Grande y bonita habitación con cocina y baño,548898239,1.470455e+18,Catu,NaN,Benito Juárez,19.394448,-99.163367,Entire home/apt,628.0,1.0,0,NaN,NaN,1,257,0,NaN
2,1414477907775396874,Ven a sentirte como en casa.,49281983,1.465751e+18,Mireya,NaN,Coyoacán,19.339362,-99.185070,Private room,499.0,1.0,0,NaN,NaN,2,158,0,NaN
3,1298027147444763745,Habitación pequeña 16,368484187,1.469744e+18,Gerardo,NaN,Miguel Hidalgo,19.461230,-99.190020,Private room,2511.0,1.0,0,NaN,NaN,2,365,0,NaN
4,1680714857095865427,Quadruple Suite with Bathroom,1680682785801540826,1.680683e+18,Halinka,NaN,Cuauhtémoc,19.420992,-99.157935,Private room,8263.0,1.0,0,NaN,NaN,2,365,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31425,1668513782034090561,Habitación privada excelente ubicación Buenavista,741668723,1.668514e+18,Kevin,NaN,Cuauhtémoc,19.448000,-99.150580,Private room,933.0,1.0,0,NaN,NaN,1,365,0,NaN
31426,1694398175149004981,Hab 3. Friends&fam cama+clóset y áreas comunes,1685078163776089732,1.685079e+18,Marie,NaN,Cuauhtémoc,19.407100,-99.163030,Private room,707.0,4.0,0,NaN,NaN,5,364,0,NaN
31427,1694382707868744808,"Habitación 1. Matrimonial, clóset, tocador y sofa",1685078163776089732,1.685079e+18,Marie,NaN,Cuauhtémoc,19.407580,-99.162510,Private room,1061.0,4.0,0,NaN,NaN,5,364,0,NaN
31428,1618288599296526432,P2 Alojamiento pequeño con cocina,739884792,1.604570e+18,Jorge GA,NaN,Venustiano Carranza,19.437680,-99.088620,Entire home/apt,NaN,2.0,0,NaN,NaN,7,0,0,NaN


In [7]:
#Verificamos información del DataFrame
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31430 entries, 0 to 31429
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   id                              31430 non-null  int64  
 1   name                            31430 non-null  str    
 2   host_id                         31430 non-null  int64  
 3   host_profile_id                 31426 non-null  float64
 4   host_name                       31425 non-null  str    
 5   neighbourhood_group             0 non-null      float64
 6   neighbourhood                   31430 non-null  str    
 7   latitude                        31430 non-null  float64
 8   longitude                       31430 non-null  float64
 9   room_type                       31430 non-null  str    
 10  price                           29637 non-null  float64
 11  minimum_nights                  31419 non-null  float64
 12  number_of_reviews               31430 non-n

In [8]:
#Convertimos el DataFrame de pandas en un arreglo de numpy
array = df.to_numpy()
array

array([[1698274831948209016, 'Roma Residence | Luxury Suite 305',
        471105419, ..., 365, 0, nan],
       [1120444645818769896,
        'Grande y bonita habitación con cocina y baño', 548898239, ...,
        257, 0, nan],
       [1414477907775396874, 'Ven a sentirte como en casa.', 49281983,
        ..., 158, 0, nan],
       ...,
       [1694382707868744808,
        'Habitación 1. Matrimonial, clóset, tocador y sofa',
        1685078163776089732, ..., 364, 0, nan],
       [1618288599296526432, 'P2 Alojamiento pequeño con cocina',
        739884792, ..., 0, 0, nan],
       [1133689320452555924, 'Departamento en la Juárez', 502955535, ...,
        186, 0, nan]], shape=(31430, 19), dtype=object)

In [ ]:
#Convertimos el DataFrame de pandas en un arreglo de numpy
array = df.to_numpy()
array

In [31]:
#Inciso A
inciso_A = array [:,[1,4,9,10]] 

In [30]:
np.savetxt("IncisoA.csv", inciso_A, delimiter=",", fmt="%s", encoding="utf-8")

In [42]:
#Inciso B
incisoB = array [:,[1]+list(range(4,19))]
incisoB 

array([['Roma Residence | Luxury Suite 305', 'Manuel', nan, ..., 365, 0,
        nan],
       ['Grande y bonita habitación con cocina y baño', 'Catu', nan, ...,
        257, 0, nan],
       ['Ven a sentirte como en casa.', 'Mireya', nan, ..., 158, 0, nan],
       ...,
       ['Habitación 1. Matrimonial, clóset, tocador y sofa', 'Marie',
        nan, ..., 364, 0, nan],
       ['P2 Alojamiento pequeño con cocina', 'Jorge GA', nan, ..., 0, 0,
        nan],
       ['Departamento en la Juárez', 'Chio', nan, ..., 186, 0, nan]],
      shape=(31430, 16), dtype=object)

In [44]:
np.savetxt("IncisoB.csv", incisoB, delimiter=",", fmt="%s", encoding="utf-8")

In [49]:
#IncisoC
IncisoC = array [[0]+list(range(50, 100))+[200, 1000, 2000, 3000, 5000]+ list(range(7000, 8001))]

In [52]:
np.savetxt("IncisoC.csv", IncisoC, delimiter=",", fmt="%s", encoding="utf-8")

In [64]:
#IncisoD
IncisoD = array[::2, 1::2]

In [65]:
np.savetxt("IncisoD.csv", IncisoD, delimiter=",", fmt="%s", encoding="utf-8")

In [66]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31430 entries, 0 to 31429
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   id                              31430 non-null  int64  
 1   name                            31430 non-null  str    
 2   host_id                         31430 non-null  int64  
 3   host_profile_id                 31426 non-null  float64
 4   host_name                       31425 non-null  str    
 5   neighbourhood_group             0 non-null      float64
 6   neighbourhood                   31430 non-null  str    
 7   latitude                        31430 non-null  float64
 8   longitude                       31430 non-null  float64
 9   room_type                       31430 non-null  str    
 10  price                           29637 non-null  float64
 11  minimum_nights                  31419 non-null  float64
 12  number_of_reviews               31430 non-n

In [72]:
#IncisoE
primosfilas = list(primerange(0,31429))
primoscolumnas = list(primerange(0,18))
IncisoE = array[np.ix_(primosfilas, primoscolumnas)]
IncisoE

array([[49281983, 1.4657505168190446e+18, nan, ..., 1.0, nan, 0],
       [368484187, 1.4697439312284754e+18, nan, ..., 1.0, nan, 0],
       [115584349, 1.4629075468365458e+18, nan, ..., 1.0, '2025-12-21',
        3],
       ...,
       [387423536, 1.4697983548428186e+18, nan, ..., 3.0, '2026-05-25',
        16],
       [739402891, 1.5960682271808084e+18, nan, ..., 1.0, '2026-05-28',
        14],
       [18679005, 1.4630589649232975e+18, nan, ..., 2.0, '2026-04-27', 3]],
      shape=(3385, 7), dtype=object)

In [73]:
np.savetxt("IncisoE.csv", IncisoE, delimiter=",", fmt="%s", encoding="utf-8")

***Indexación de un array 1D a partir de un array 2D***

In [9]:
# Acceder a la primera fila de un arreglo de numpy
fila0 = array[0]
fila0

array([1698274831948209016, 'Roma Residence | Luxury Suite 305',
       471105419, 1.4701247982138043e+18, 'Manuel', nan, 'Cuauhtémoc',
       19.406572, -99.1630906, 'Entire home/apt', 2066.0, 1.0, 0, nan,
       nan, 42, 365, 0, nan], dtype=object)

In [10]:
# Acceder a la primera fila de un Dataframe de pandas
fila0 = df.iloc[0]
fila0

id                                              1698274831948209016
name                              Roma Residence | Luxury Suite 305
host_id                                                   471105419
host_profile_id                               1470124798213804288.0
host_name                                                    Manuel
neighbourhood_group                                             NaN
neighbourhood                                            Cuauhtémoc
latitude                                                  19.406572
longitude                                                -99.163091
room_type                                           Entire home/apt
price                                                        2066.0
minimum_nights                                                  1.0
number_of_reviews                                                 0
last_review                                                     NaN
reviews_per_month                               

In [21]:
# Acceder a la primera fila de un arreglo de numpy
columna0 = array[:, 0]
columna0

array([1698274831948209016, 1120444645818769896, 1414477907775396874, ...,
       1694382707868744808, 1618288599296526432, 1133689320452555924],
      shape=(31430,), dtype=object)

***Indexación de múltiples arrays 1D a partir de un array 2D***

In [12]:
#Filas consecutivas 3-5 y la columna 4
Filas_3_a_5= array[3:6, 4]       
Filas_3_a_5

array(['Gerardo', 'Halinka', 'Abel'], dtype=object)

In [13]:
#Filas no consecutivas 2, 8, 12 y Todas las columnas
Filas_3_a_5= array[[2, 8, 12], :]       
Filas_3_a_5

array([[1414477907775396874, 'Ven a sentirte como en casa.', 49281983,
        1.4657505168190446e+18, 'Mireya', nan, 'Coyoacán',
        19.33936193517208, -99.18507003352676, 'Private room', 499.0,
        1.0, 0, nan, nan, 2, 158, 0, nan],
       [1448599299281112727, 'Céntrico, seguro y acogedor', 511603454,
        1.4703006156679316e+18, 'Pablo Alejandro', nan, 'Miguel Hidalgo',
        19.4344, -99.17163, 'Private room', 987.0, 2.0, 0, nan, nan, 1,
        320, 0, nan],
       [1547637190139759585, 'Casa Tarango', 93943242,
        1.4671335844683548e+18, 'Gustavo', nan, 'Álvaro Obregón',
        19.362400135853463, -99.22287827070636, 'Entire home/apt',
        1855.0, 4.0, 5, '2026-05-13', 1.14, 5, 241, 5, nan]], dtype=object)

In [14]:
#Filas combinadas 0, 4-6 y 10 y columna 4
Filas_0_4_5_6_10= array[[0] + list(range(4, 7)) + [10], 4]       
Filas_0_4_5_6_10


array(['Manuel', 'Halinka', 'Abel', 'Casa', 'Hotel Boutique Venecia Cdmx'],
      dtype=object)

In [15]:
#Filas pares y todas las columnas
Filas_pares = array[::2, :]
Filas_pares

array([[1698274831948209016, 'Roma Residence | Luxury Suite 305',
        471105419, ..., 365, 0, nan],
       [1414477907775396874, 'Ven a sentirte como en casa.', 49281983,
        ..., 158, 0, nan],
       [1680714857095865427, 'Quadruple Suite with Bathroom',
        1680682785801540826, ..., 365, 0, nan],
       ...,
       [1666317923695679135, 'Elegant light-filled apartment on Reforma',
        185233439, ..., 1, 0, nan],
       [1694398175149004981,
        'Hab 3. Friends&fam cama+clóset y áreas comunes',
        1685078163776089732, ..., 364, 0, nan],
       [1618288599296526432, 'P2 Alojamiento pequeño con cocina',
        739884792, ..., 0, 0, nan]], shape=(15715, 19), dtype=object)

In [16]:
#Filas impares y todas las columnas
Filas_impares = array[1::2, :]
Filas_impares

array([[1120444645818769896,
        'Grande y bonita habitación con cocina y baño', 548898239, ...,
        257, 0, nan],
       [1298027147444763745, 'Habitación pequeña 16', 368484187, ...,
        365, 0, nan],
       [1168174173941960570, 'Descanso en centro cdmx', 115584349, ...,
        88, 3, nan],
       ...,
       [1668513782034090561,
        'Habitación privada excelente ubicación Buenavista', 741668723,
        ..., 365, 0, nan],
       [1694382707868744808,
        'Habitación 1. Matrimonial, clóset, tocador y sofa',
        1685078163776089732, ..., 364, 0, nan],
       [1133689320452555924, 'Departamento en la Juárez', 502955535, ...,
        186, 0, nan]], shape=(15715, 19), dtype=object)

In [17]:
#Filas primas y todas las columnas
primos = list(primerange(0, 20))
Filas_primas = array[primos, :]
Filas_primas

array([[1414477907775396874, 'Ven a sentirte como en casa.', 49281983,
        1.4657505168190446e+18, 'Mireya', nan, 'Coyoacán',
        19.33936193517208, -99.18507003352676, 'Private room', 499.0,
        1.0, 0, nan, nan, 2, 158, 0, nan],
       [1298027147444763745, 'Habitación pequeña 16', 368484187,
        1.4697439312284754e+18, 'Gerardo', nan, 'Miguel Hidalgo',
        19.46123, -99.19002, 'Private room', 2511.0, 1.0, 0, nan, nan, 2,
        365, 0, nan],
       [1168174173941960570, 'Descanso en centro cdmx', 115584349,
        1.4629075468365458e+18, 'Abel', nan, 'Cuauhtémoc', 19.42847,
        -99.14749, 'Private room', 2283.0, 1.0, 7, '2025-12-21', 0.35, 2,
        88, 3, nan],
       [981283913392111849, 'Green Suite in Casa Pani', 305540724,
        1.4695641500460526e+18, 'Casa', nan, 'Cuauhtémoc',
        19.432591170988385, -99.17081658738874, 'Private room', 1656.0,
        1.0, 0, nan, nan, 6, 326, 0, nan],
       [1704592774041201920,
        'Alojamiento para 2 a

In [18]:
#Convertir un arreglo de numpy a CSV
np.savetxt("datos_numpy.csv", array, delimiter=",", fmt="%s", encoding="utf-8")

In [19]:
#Convertir un dataframe de pandas a CSV
df.to_csv("datos_pandas.csv")